
const S=(q,el=document)=>el.querySelector(q), SS=(q,el=document)=>[...el.querySelectorAll(q)];
const state={products:[],rates:null,shownCurrency:'USD',currencies:['USD','NOK','EUR','GBP','SEK','DKK','AUD','CAD']};
let config={amazon_tag:'',temu_affiliate_id:'',utm_source:'buzzkart',admin_password:'CHANGE_ME'};

async function loadConfig(){try{const r=await fetch('config.json');config=await r.json();}catch(e){}}
async function loadRates(){try{const r=await fetch('https://api.exchangerate.host/latest?base=USD');const j=await r.json();state.rates=j.rates||null}catch(e){}}
function money(usd){const v=Number(usd||0);const cur=state.shownCurrency;let out=`$${v.toFixed(2)} USD`;if(state.rates&&state.rates[cur]){const x=v*state.rates[cur];if(cur!=='USD')out+=` • ≈ ${x.toFixed(0)} ${cur}`;}if(cur!=='NOK'&&state.rates&&state.rates.NOK){out+=` • ≈ ${(v*state.rates.NOK).toFixed(0)} NOK`;}return out;}
function applyAffiliate(url){try{const u=new URL(url);if(u.hostname.includes('amazon.')&&config.amazon_tag&&!u.searchParams.get('tag'))u.searchParams.set('tag',config.amazon_tag);if(u.hostname.includes('temu.')&&config.temu_affiliate_id&&!u.searchParams.get('affiliateId'))u.searchParams.set('affiliateId',config.temu_affiliate_id);if(config.utm_source&&!u.searchParams.get('utm_source'))u.searchParams.set('utm_source',config.utm_source);return u.toString()}catch(e){const j=url.includes('?')?'&':'?';return url+j+'utm_source='+(encodeURIComponent(config.utm_source||'buzzkart'))}}
function hashtags(p){const base=['#viral','#deal','#shopping','#tiktokmademebuyit'];if(p.source)base.push('#'+p.source);(p.categories||[]).forEach(c=>base.push('#'+c.toLowerCase()));return (p.tags||base).slice(0,10).join(' ')}
function renderFeed(list){const mount=S('.feed');mount.innerHTML='';list.forEach(p=>{const post=document.createElement('article');post.className='post';const media=document.createElement('div');media.className='media';if(p.video){const v=document.createElement('video');v.controls=true;v.muted=true;v.playsInline=true;v.loop=true;v.autoplay=true;v.src=p.video;media.appendChild(v);}else{const img=document.createElement('img');img.src=p.image;img.alt=p.title;media.appendChild(img);}post.appendChild(media);const cap=document.createElement('div');cap.className='caption';const row=document.createElement('div');row.className='row';const t=document.createElement('div');t.className='title';t.textContent=p.title;const pr=document.createElement('div');pr.className='price';pr.textContent=money(p.price_usd);row.appendChild(t);row.appendChild(pr);const desc=document.createElement('div');desc.textContent=p.description||'';const tagEl=document.createElement('div');tagEl.className='hashtags';tagEl.textContent=hashtags(p);const actions=document.createElement('div');actions.className='actions';const like=document.createElement('button');like.textContent='♥';like.title='Like';like.addEventListener('click',()=>{like.textContent = like.textContent==='♥'?'❤️':'♥';});const share=document.createElement('button');share.textContent='⤴';share.title='Share';share.addEventListener('click',()=>{const link=location.origin+location.pathname.replace(/\/[^/]*$/,'')+'p/'+encodeURIComponent(p.id)+'.html';navigator.clipboard.writeText(link);alert('Link copied: '+link)});actions.append(like,share);const shop=document.createElement('button');shop.className='fabshop';shop.textContent='Shop';shop.addEventListener('click',()=>window.open(applyAffiliate(p.url),'_blank'));post.append(actions);post.append(shop);cap.append(row,desc,tagEl);post.appendChild(cap); // click anywhere
post.addEventListener('click',(e)=>{if(e.target.tagName.toLowerCase()==='button')return; window.open(applyAffiliate(p.url),'_blank');}); mount.appendChild(post);});}
function sortForYou(list){try{const pref=JSON.parse(localStorage.getItem('bz_pref')||'{}');const cat=pref.cat||{};const src=pref.src||{};return [...list].sort((a,b)=>{const as=(src[a.source]||0)+(a.categories||[]).reduce((t,c)=>t+(cat[c]||0),0);const bs=(src[b.source]||0)+(b.categories||[]).reduce((t,c)=>t+(cat[c]||0),0);return bs-as || (b.added_at||0)-(a.added_at||0);});}catch(e){return list}}
function trackClick(p){try{const pref=JSON.parse(localStorage.getItem('bz_pref')||'{}');pref.cat=pref.cat||{};pref.src=pref.src||{};(p.categories||[]).forEach(c=>pref.cat[c]=(pref.cat[c]||0)+1);pref.src[p.source]=(pref.src[p.source]||0)+1;localStorage.setItem('bz_pref',JSON.stringify(pref));}catch(e){}}
async function init(){await loadConfig();const themeBtn=S('#themeToggle');themeBtn&&themeBtn.addEventListener('click',()=>document.body.classList.toggle('light'));const curSel=S('#currency');if(curSel){state.currencies.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;curSel.appendChild(o)});curSel.value='USD';curSel.addEventListener('change',e=>{state.shownCurrency=e.target.value;render()});}await loadRates();try{const r=await fetch('products.json');state.products=await r.json()}catch(e){state.products=[]}render()}
function render(){const mount=S('.feed');if(!mount)return;let list=[...state.products];const page=document.body.dataset.page||'foryou';if(page==='foryou'){list=sortForYou(list);}else if(page==='temu'||page==='aliexpress'||page==='amazon'||page==='pod'){list=list.filter(p=>p.source===page);}list=list.sort(()=>Math.random()-0.5); // daily shuffle feel
renderFeed(list);const cnt=S('#count');if(cnt)cnt.textContent=list.length;SS('.post').forEach((post,i)=>{post.addEventListener('click',()=>{const id=state.products[i];});});}
window.addEventListener('DOMContentLoaded',init);
